### ISSUE TITLE
ValueError: Cannot convert NA to integer

### ISSUE THREAD

**Issue by fighting41love** [JasonKessler/fakeout#1]
Run function news_type_viz()
Got the ValueError: Cannot convert NA to integer

I have tried many solutions... I don't know how to solve the problem.

**Comment by JasonKessler** [comment]
Thanks for checking out the notebook.  Unfortunately, I don't have enough context to recreate your bug.

What I'd need is:
- The code and data you're running
- Which call of the function leads to an error
- The full error you get
- Your python environment and version
- The versions of the relevant packages

**Comment by fighting41love** [comment]
Thanks for your response.  
Python 3.5 on Mac OS sierra.

Here is the code (the indent in the following code is not right, you can download the code from https://drive.google.com/open?id=0B3e3qZpPtccsT2NqNWRSYWdiUjA):
`import spacy`
`import pandas as pd`
`from scattertext import produce_scattertext_explorer`
`from scattertext.CorpusFromPandas import CorpusFromPandas`

`nlp = spacy.en.English()`
`fields = ['type','text']`
`convention_df = pd.read_csv('data.csv',nrows=2,usecols= fields)`
`ddf = convention_df`
`corpus = CorpusFromPandas(ddf,`
                          `category_col='type',`
                         `text_col='text',`
                          `nlp=nlp).build()`

`html = produce_scattertext_explorer(corpus,`
                                    `category='real',`
                                    `category_name='real',`
                                    `not_category_name='fake',`
                                    `minimum_term_frequency=5,`
                                    `pmi_filter_thresold=4,`
                                    `width_in_pixels=1000,`
                                    `metadata=ddf['text'])`
`open('./demo.html', 'wb').write(html.encode('utf-8'))`
`print('Open ./demo.html in Chrome or Firefox.')`


The data.csv can be downloaded from the google drive.
https://drive.google.com/open?id=0B3e3qZpPtccsMUdmdjVYVWFtVHM


The error is as follows:
Traceback (most recent call last):
  File "/Users/yy/PycharmProjects/merge_csv/plot_words.py", line 22, in <module>
    metadata=ddf['text'])
  File "/Users/yy/anaconda/lib/python3.5/site-packages/scattertext/__init__.py", line 224, in produce_scattertext_explorer
    metadata=metadata)
  File "/Users/yy/anaconda/lib/python3.5/site-packages/scattertext/ScatterChartExplorer.py", line 55, in to_dict
    transform=transform)
  File "/Users/yy/anaconda/lib/python3.5/site-packages/scattertext/ScatterChart.py", line 128, in to_dict
    self._add_term_freq_to_json_df(json_df, df, category)
  File "/Users/yy/anaconda/lib/python3.5/site-packages/scattertext/ScatterChartExplorer.py", line 76, in _add_term_freq_to_json_df
    ScatterChart._add_term_freq_to_json_df(self, json_df, term_freq_df, category)
  File "/Users/yy/anaconda/lib/python3.5/site-packages/scattertext/ScatterChart.py", line 167, in _add_term_freq_to_json_df
    .apply(np.round).astype(np.int))
  File "/Users/yy/anaconda/lib/python3.5/site-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/Users/yy/anaconda/lib/python3.5/site-packages/pandas/core/internals.py", line 3189, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/Users/yy/anaconda/lib/python3.5/site-packages/pandas/core/internals.py", line 3056, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/yy/anaconda/lib/python3.5/site-packages/pandas/core/internals.py", line 461, in astype
    values=values, **kwargs)
  File "/Users/yy/anaconda/lib/python3.5/site-packages/pandas/core/internals.py", line 504, in _astype
    values = _astype_nansafe(values.ravel(), dtype, copy=True)
  File "/Users/yy/anaconda/lib/python3.5/site-packages/pandas/types/cast.py", line 531, in _astype_nansafe
    raise ValueError('Cannot convert NA to integer')
ValueError: Cannot convert NA to integer

**Comment by JasonKessler** [comment]
You need to have documents in both categories for the visualization to work.   You just have two documents in the "real" category. 

Also, the meta field should just be a short 'headline' about the document, not the full text.  You can always leave it out.

**Comment by JasonKessler** [comment]
You should lower the minimum term frequencies as well. 

It sounds like this is an really an issue with using Scattertext, so I'm going to close this.  Feel free to open an issue in that repo, but please read the documentation first.

**Comment by fighting41love** [comment]
I solved the problem by setting the encoding = 'utf8' in read_csv() function, and using the df['text'].apply(chinese_nlp) as shown in the demo_chinese.py. （My csv data is english.）

Thanks for your patience and advice!
I will cite this in my paper. It is a very interesting and useful tool.
Thanks!

**Comment by JasonKessler** [comment]
Awesome.  Thanks in advance for the cite.
